//
//  DefaultSearchTerms.swift
//  RecipeRandomizer
//
//  Created by Luis Antonio Rodriguez on 2/19/16.
//  Copyright © 2016 Luis Antonio Rodriguez. All rights reserved.
//

import Foundation

var DefaultSearchTerms = ["All-Purpose Flour",
    "Allspice",
    "Almonds",
    "Apples",
    "Apricots",
    "Baking Powder",
    "Baking Soda",
    "Barley",
    "Bay Leaves",
    "Bell Pepper",
    "Black",
    "Black Pepper",
    "Blackberries",
    "Blueberries",
    "Broccoli",
    "Brown Sugar",
    "Butter",
    "Canned And Paste",
    "Canned Tomatoes",
    "Cannellini",
    "Capers",
    "Cayenne Pepper",
    "Cheese",
    "Chickpeas",
    "Chili Powder",
    "Cinnamon",
    "Cloves",
    "Corn",
    "Corn Tortillas",
    "Cornstarch",
    "Couscous",
    "Crushed Red Pepper",
    "Cumin",
    "Curry Powder",
    "Dried Lentils",
    "Edamame",
    "Feta",
    "Garlic",
    "Ginger",
    "Granulated Sugar",
    "Ground Coriander",
    "Honey",
    "Italian Seasoning",
    "Kidney",
    "Kosher Salt",
    "Large Eggs",
    "Stock Or Broth",
    "Milk",
    "Millet",
    "Mozzarella",
    "Nutmeg",
    "Olives",
    "Oregano",
    "Panko",
    "Paprika",
    "Parmesan",
    "Pasta",
    "Peaches",
    "Peanut Butter",
    "Peanuts",
    "Peas",
    "Plain Yogurt",
    "Potatoes",
    "Preserves Or Jelly",
    "Quinoa Or Wheatberries",
    "Raisins",
    "Red Onions",
    "Regular Breadcrumbs",
    "Rice",
    "Rolled Oats",
    "Rosemary",
    "Salsa",
    "Sharp Cheddar",
    "Spinach",
    "Strawberries",
    "Sunflower",
    "Thyme Leaves",
    "Tomatoes",
    "Tuna Fish",
    "Vanilla Extract",
    "Walnuts",
    "Whole Wheat Pasta",
    "Yellow Onions"]