//
//  DefaultSearchTerms.swift
//  RecipeRandomizer
//
//  Created by Luis Antonio Rodriguez on 2/19/16.
//  Copyright © 2016 Luis Antonio Rodriguez. All rights reserved.
//

import Foundation

var DefaultSearchTerms = ["--",
    "All-Purpose Flour",
    "Allspice",
    "Almonds",
    "Apples",
    "Apricots",
    "Baking Powder",
    "Baking Soda",
    "Barley",
    "Bay Leaves",
    "Bell Pepper",
    "Black",
    "Black Pepper",
    "Blackberries",
    "Blueberries",
    "Breadcrumbs",
    "Broccoli",
    "Brown Sugar",
    "Butter",
    "Canned Tomatoes",
    "Cannellini",
    "Capers",
    "Cayenne Pepper",
    "Cheese",
    "Chickpeas",
    "Chili Powder",
    "Cinnamon",
    "Cloves",
    "Corn",
    "Corn Tortillas",
    "Cornstarch",
    "Couscous",
    "Crushed Red Pepper",
    "Cumin",
    "Curry Powder",
    "Dried Lentils",
    "Edamame",
    "Feta",
    "Garlic",
    "Ginger",
    "Granulated Sugar",
    "Ground Coriander",
    "Honey",
    "Italian Seasoning",
    "Jelly",
    "Kidney",
    "Kosher Salt",
    "Large Eggs",
    "Milk",
    "Millet",
    "Mozzarella",
    "Nutmeg",
    "Olives",
    "Oregano",
    "Panko",
    "Paprika",
    "Parmesan",
    "Pasta",
    "Peaches",
    "Peanut Butter",
    "Peanuts",
    "Peas",
    "Plain Yogurt",
    "Potatoes",
    "Preserves",
    "Quinoa",
    "Raisins",
    "Red Onions",
    "Rice",
    "Rolled Oats",
    "Rosemary",
    "Salsa",
    "Sharp Cheddar",
    "Spinach",
    "Strawberries",
    "Sunflower",
    "Thyme Leaves",
    "Tomatoes",
    "Tomato Paste",
    "Tuna Fish",
    "Vanilla Extract",
    "Walnuts",
    "Wheatberries",
    "Whole Wheat Pasta",
    "Yellow Onions"]