window.data = {
    "coins": [{
        "id": "mc00285279",
        "coinTypeId": "ct28857485",
        "active": true,
        "premium": "1.2",
        "purchaseDate": "03/06/2015",
        "purchasePrice": "11.43",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc01916821",
        "coinTypeId": "ct45860574",
        "active": true,
        "premium": "7",
        "purchaseDate": "05/20/2015",
        "purchasePrice": "10",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc02580203",
        "coinTypeId": "ct73704560",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "10/24/2015",
        "purchasePrice": "16.54",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc02593189",
        "coinTypeId": "ct78297046",
        "active": true,
        "premium": "4",
        "purchaseDate": "05/31/2015",
        "purchasePrice": "14.975",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc03475717",
        "coinTypeId": "ct80375315",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc03729185",
        "coinTypeId": "ct30773496",
        "active": true,
        "premium": "10",
        "purchaseDate": "05/20/2015",
        "purchasePrice": "7",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc03824343",
        "coinTypeId": "ct65845301",
        "active": true,
        "premium": "2",
        "purchaseDate": "07/18/2015",
        "purchasePrice": "14.58",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc04560237",
        "coinTypeId": "mc87359291",
        "active": true,
        "premium": "1",
        "purchaseDate": "10/03/2015",
        "purchasePrice": 19.5,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc05516357",
        "coinTypeId": "ct93859603",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc05645900",
        "coinTypeId": "ct99542018",
        "active": true,
        "premium": "1.4",
        "purchaseDate": "06/26/2015",
        "purchasePrice": "19.47",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc06015226",
        "coinTypeId": "ct32014901",
        "active": true,
        "premium": "1",
        "purchaseDate": "04/05/2015",
        "purchasePrice": "20.415",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc07342164",
        "coinTypeId": "ct38676191",
        "active": true,
        "premium": "4",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "7",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc07544931",
        "coinTypeId": "ct63345213",
        "active": true,
        "premium": "13",
        "purchaseDate": "10/03/2015",
        "purchasePrice": "8.49",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc07648699",
        "coinTypeId": "ct66931955",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc08060853",
        "coinTypeId": "ct03395421",
        "active": true,
        "premium": "1.6",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "10",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc09330773",
        "coinTypeId": "ct03395421",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc09768418",
        "coinTypeId": "ct30726160",
        "active": true,
        "premium": "1.45",
        "purchaseDate": "04/24/2015",
        "purchasePrice": "19.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc09806183",
        "coinTypeId": "ct57021566",
        "active": true,
        "premium": "1.3",
        "purchaseDate": "05/30/2015",
        "purchasePrice": "40",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc10567866",
        "coinTypeId": "ct47283102",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc10797313",
        "coinTypeId": "ct98328452",
        "active": true,
        "premium": "1",
        "purchaseDate": "07/26/2015",
        "purchasePrice": "20.85",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc12059703",
        "coinTypeId": "ct20170447",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc12615906",
        "coinTypeId": "ct44182242",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc12933015",
        "coinTypeId": "ct63335213",
        "active": true,
        "premium": "7",
        "purchaseDate": "10/04/2015",
        "purchasePrice": "12.95",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc13938246",
        "coinTypeId": "ct08254404",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "09/28/2015",
        "purchasePrice": "22.45",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc14256597",
        "coinTypeId": "ct77605757",
        "active": true,
        "premium": "1.73",
        "purchaseDate": "09/27/2015",
        "purchasePrice": "22.95",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc14384116",
        "coinTypeId": "ct63874757",
        "active": true,
        "premium": "1",
        "purchaseDate": "10/03/2015",
        "purchasePrice": 19.5,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc14965946",
        "coinTypeId": "mc87359291",
        "active": true,
        "premium": "1",
        "purchaseDate": "10/03/2015",
        "purchasePrice": 19.5,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc15221339",
        "coinTypeId": "ct98328452",
        "active": false,
        "premium": "1",
        "purchaseDate": "07/26/2015",
        "purchasePrice": "20.85",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc15382434",
        "coinTypeId": "ct78096558",
        "active": true,
        "premium": "2",
        "purchaseDate": "05/28/2015",
        "purchasePrice": "31.16",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc16040930",
        "coinTypeId": "ct11919037",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "09/28/2015",
        "purchasePrice": "22.45",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc16498408",
        "coinTypeId": "ct62921249",
        "active": false,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc16604928",
        "coinTypeId": "ct63325213",
        "active": true,
        "premium": "7",
        "purchaseDate": "10/09/2015",
        "purchasePrice": "8.49",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc18042121",
        "coinTypeId": "ct17546876",
        "active": true,
        "premium": "1.2",
        "purchaseDate": "07/16/2015",
        "purchasePrice": "167.45",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc18145962",
        "coinTypeId": "ct98328452",
        "active": true,
        "premium": "1",
        "purchaseDate": "07/26/2015",
        "purchasePrice": "20.85",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc18653817",
        "coinTypeId": "ct90311804",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "05/30/2015",
        "purchasePrice": "25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc18870743",
        "coinTypeId": "ct01021621",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "06/25/2015",
        "purchasePrice": "26",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc19036583",
        "coinTypeId": "mc87359291",
        "active": true,
        "premium": "1.4",
        "purchaseDate": "12/25/2015",
        "purchasePrice": "18.2",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc19395577",
        "coinTypeId": "ct95447310",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc19958306",
        "coinTypeId": "ct81285961",
        "active": true,
        "premium": "2.08",
        "purchaseDate": "06/26/2015",
        "purchasePrice": "60.43",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc20360758",
        "coinTypeId": "ct08254004",
        "active": true,
        "premium": "1.84",
        "purchaseDate": "04/30/2015",
        "purchasePrice": "27",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc20494318",
        "coinTypeId": "ct08254404",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "09/28/2015",
        "purchasePrice": "22.45",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc20506522",
        "coinTypeId": "ct59717514",
        "active": true,
        "premium": "1.645",
        "purchaseDate": "04/02/2015",
        "purchasePrice": "24",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc20711999",
        "coinTypeId": "ct11082869",
        "active": true,
        "premium": "1.3",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc20760440",
        "coinTypeId": "ct03395421",
        "active": true,
        "premium": "1.6",
        "purchaseDate": "02/13/2016",
        "purchasePrice": "12",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc21320360",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc21714629",
        "coinTypeId": "ct59330439",
        "active": true,
        "premium": "10",
        "purchaseDate": "05/26/2015",
        "purchasePrice": "7.90",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc22229106",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "02/08/2016",
        "purchasePrice": "20.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc22247512",
        "coinTypeId": "ct74472416",
        "active": false,
        "premium": "1.24",
        "purchaseDate": "04/20/2015",
        "purchasePrice": "18.7",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc22404706",
        "coinTypeId": "ct38826467",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "05/28/2015",
        "purchasePrice": "42.54",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc22556917",
        "coinTypeId": "ct77065970",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "5",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc23005058",
        "coinTypeId": "ct48297131",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "05/05/2015",
        "purchasePrice": "23",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc23060716",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "02/08/2016",
        "purchasePrice": "20.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc23633811",
        "coinTypeId": "ct20885143",
        "active": true,
        "premium": "8",
        "purchaseDate": "04/14/2015",
        "purchasePrice": "5.5",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc23915505",
        "coinTypeId": "ct98328452",
        "active": false,
        "premium": "1",
        "purchaseDate": "07/26/2015",
        "purchasePrice": "20.85",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc24927082",
        "coinTypeId": "ct08254004",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc25009178",
        "coinTypeId": "ct08254404",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "09/28/2015",
        "purchasePrice": "22.45",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc25469153",
        "coinTypeId": "ct21984109",
        "active": true,
        "premium": "5",
        "purchaseDate": "08/29/2015",
        "purchasePrice": "31",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc26456491",
        "coinTypeId": "ct15191701",
        "active": false,
        "premium": "1.2",
        "purchaseDate": "04/05/2015",
        "purchasePrice": "19.505",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc26717992",
        "coinTypeId": "ct63873757",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc26889058",
        "coinTypeId": "ct74472416",
        "active": true,
        "premium": "1.24",
        "purchaseDate": "04/20/2015",
        "purchasePrice": "18.7",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc28473209",
        "coinTypeId": "ct77065970",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "5",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc29182955",
        "coinTypeId": "ct49264661",
        "active": true,
        "premium": "1.6",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "10",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc29345800",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "02/08/2016",
        "purchasePrice": "20.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc30194717",
        "coinTypeId": "ct03395421",
        "active": true,
        "premium": "1.6",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "10",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc30262614",
        "coinTypeId": "ct30726160",
        "active": true,
        "premium": "1.45",
        "purchaseDate": "04/24/2015",
        "purchasePrice": "19.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc30488418",
        "coinTypeId": "ct71587476",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "04/05/2015",
        "purchasePrice": "23",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc30512452",
        "coinTypeId": "ct17114119",
        "active": true,
        "premium": "1.6",
        "purchaseDate": "10/01/2015",
        "purchasePrice": "18",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc31099362",
        "coinTypeId": "ct45860574",
        "active": true,
        "premium": "7",
        "purchaseDate": "05/20/2015",
        "purchasePrice": "10",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc31594000",
        "coinTypeId": "ct78096558",
        "active": true,
        "premium": "2",
        "purchaseDate": "04/28/2015",
        "purchasePrice": "31.07",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc31936407",
        "coinTypeId": "ct03969878",
        "active": true,
        "premium": "1.4",
        "purchaseDate": "03/25/2015",
        "purchasePrice": "22.05",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc32034635",
        "coinTypeId": "ct74472416",
        "active": false,
        "premium": "1.24",
        "purchaseDate": "04/20/2015",
        "purchasePrice": "18.7",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc32118232",
        "coinTypeId": "ct69138694",
        "active": false,
        "premium": "2",
        "purchaseDate": "05/31/2015",
        "purchasePrice": "26.36",
        "saleDate": "06/07/2015",
        "salePrice": "0",
        "isPermaStack": false
    }, {
        "id": "mc32187959",
        "coinTypeId": "ct89115132",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "07/30/2015",
        "purchasePrice": "24.31",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc32379739",
        "coinTypeId": "ct00317870",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "06/25/2015",
        "purchasePrice": "13",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc32398915",
        "coinTypeId": "ct98328452",
        "active": true,
        "premium": "1",
        "purchaseDate": "07/26/2015",
        "purchasePrice": "20.85",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc33825233",
        "coinTypeId": "ct98328452",
        "active": false,
        "premium": "1",
        "purchaseDate": "07/26/2015",
        "purchasePrice": "20.85",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc34225220",
        "coinTypeId": "ct24990040",
        "active": false,
        "premium": "1.2",
        "purchaseDate": "04/05/2015",
        "purchasePrice": "019.005",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc36997735",
        "coinTypeId": "ct89115132",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "07/30/2015",
        "purchasePrice": "24.31",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc37086874",
        "coinTypeId": "ct96533562",
        "active": true,
        "premium": "1.15",
        "purchaseDate": "05/21/2015",
        "purchasePrice": "107",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc37613416",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "02/08/2016",
        "purchasePrice": "20.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc38029716",
        "coinTypeId": "ct30773496",
        "active": true,
        "premium": "10",
        "purchaseDate": "05/20/2015",
        "purchasePrice": "7",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc38213304",
        "coinTypeId": "ct30726160",
        "active": true,
        "premium": "1.45",
        "purchaseDate": "04/24/2015",
        "purchasePrice": "19.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc38285763",
        "coinTypeId": "ct19401019",
        "active": true,
        "premium": "1",
        "purchaseDate": "11/18/2015",
        "purchasePrice": "9",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc38291767",
        "coinTypeId": "ct87596361",
        "active": true,
        "premium": "3.5",
        "purchaseDate": "08/25/2015",
        "purchasePrice": "24.95",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc38426151",
        "coinTypeId": "ct43829769",
        "active": true,
        "premium": "3",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "9",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc38857939",
        "coinTypeId": "ct08166697",
        "active": true,
        "premium": "3",
        "purchaseDate": "10/24/2015",
        "purchasePrice": "3.98",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc39244214",
        "coinTypeId": "ct20885143",
        "active": true,
        "premium": "8",
        "purchaseDate": "04/14/2015",
        "purchasePrice": "5.5",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc39927412",
        "coinTypeId": "ct65193802",
        "active": true,
        "premium": "1.2",
        "purchaseDate": "07/30/2015",
        "purchasePrice": "17.61",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc39996960",
        "coinTypeId": "ct08254004",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc40128738",
        "coinTypeId": "ct99542018",
        "active": true,
        "premium": "1.4",
        "purchaseDate": "06/26/2015",
        "purchasePrice": "19.47",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc40614733",
        "coinTypeId": "ct37914629",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc40679460",
        "coinTypeId": "ct74472416",
        "active": false,
        "premium": "1.24",
        "purchaseDate": "04/20/2015",
        "purchasePrice": "18.7",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc40807724",
        "coinTypeId": "ct27664483",
        "active": true,
        "premium": "2",
        "purchaseDate": "09/03/2015",
        "purchasePrice": "61",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc42588839",
        "coinTypeId": "ct17598979",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc42616183",
        "coinTypeId": "ct25537124",
        "active": true,
        "premium": "1.6",
        "purchaseDate": "07/30/2015",
        "purchasePrice": "43.63",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc44064439",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "02/08/2016",
        "purchasePrice": "20.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc44085891",
        "coinTypeId": "ct28857485",
        "active": true,
        "premium": "1.2",
        "purchaseDate": "03/06/2015",
        "purchasePrice": "10.98",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc44183684",
        "coinTypeId": "ct56306150",
        "active": true,
        "premium": "2.5",
        "purchaseDate": "06/11/2015",
        "purchasePrice": "26.21",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc44927230",
        "coinTypeId": "ct65841055",
        "active": true,
        "premium": "2.5",
        "purchaseDate": "08/12/2015",
        "purchasePrice": "38.99",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc44951166",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc45107307",
        "coinTypeId": "ct36352600",
        "active": true,
        "premium": "1.41",
        "purchaseDate": "07/16/2015",
        "purchasePrice": "106.95",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc45257194",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "02/08/2016",
        "purchasePrice": "20.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc46464825",
        "coinTypeId": "ct28003062",
        "active": true,
        "premium": "2",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc46592852",
        "coinTypeId": "ct03395421",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc47514270",
        "coinTypeId": "ct74472416",
        "active": true,
        "premium": "1.24",
        "purchaseDate": "04/20/2015",
        "purchasePrice": "18.7",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc47652092",
        "coinTypeId": "ct20885143",
        "active": true,
        "premium": "8",
        "purchaseDate": "04/14/2015",
        "purchasePrice": "5.5",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc47940170",
        "coinTypeId": "ct51188092",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc48044971",
        "coinTypeId": "ct98804651",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc49089629",
        "coinTypeId": "ct19265545",
        "active": false,
        "premium": "1.2",
        "purchaseDate": "05/10/2015",
        "purchasePrice": "206",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc49435731",
        "coinTypeId": "mc30447922",
        "active": true,
        "premium": "1",
        "purchaseDate": "10/03/2015",
        "purchasePrice": 19.5,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc49491321",
        "coinTypeId": "ct11451255",
        "active": true,
        "premium": "1.6",
        "purchaseDate": "05/24/2015",
        "purchasePrice": "49.49",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc49637641",
        "coinTypeId": "ct77483911",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc49673982",
        "coinTypeId": "ct30726160",
        "active": true,
        "premium": "1.45",
        "purchaseDate": "04/24/2015",
        "purchasePrice": "19.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc50102091",
        "coinTypeId": "ct08537300",
        "active": true,
        "premium": "2.8",
        "purchaseDate": "08/16/2015",
        "purchasePrice": "20.50",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc50320385",
        "coinTypeId": "ct08254404",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "09/28/2015",
        "purchasePrice": "22.45",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc50364519",
        "coinTypeId": "ct77065970",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "5",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc50556326",
        "coinTypeId": "ct03395421",
        "active": true,
        "premium": "1.6",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "10",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc50988974",
        "coinTypeId": "ct30773496",
        "active": true,
        "premium": "10",
        "purchaseDate": "05/20/2015",
        "purchasePrice": "7",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc51806868",
        "coinTypeId": "ct16757622",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc51874676",
        "coinTypeId": "ct02559777",
        "active": true,
        "premium": "2",
        "purchaseDate": "02/13/2016",
        "purchasePrice": "9",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc52149009",
        "coinTypeId": "ct97233002",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc52247355",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc52480842",
        "coinTypeId": "ct30726160",
        "active": true,
        "premium": "1.45",
        "purchaseDate": "04/24/2015",
        "purchasePrice": "19.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc52572010",
        "coinTypeId": "ct68985861",
        "active": true,
        "premium": "1",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "6",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc52848001",
        "coinTypeId": "ct59330439",
        "active": true,
        "premium": "10",
        "purchaseDate": "08/30/2015",
        "purchasePrice": "7.9",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc53528249",
        "coinTypeId": "ct78096558",
        "active": true,
        "premium": "2",
        "purchaseDate": "03/20/2015",
        "purchasePrice": "32.92",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc53784782",
        "coinTypeId": "ct99542018",
        "active": true,
        "premium": "1",
        "purchaseDate": "10/03/2015",
        "purchasePrice": 19.5,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc53981708",
        "coinTypeId": "ct77483911",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc54333721",
        "coinTypeId": "ct78297046",
        "active": true,
        "premium": "4",
        "purchaseDate": "05/31/2015",
        "purchasePrice": "14.975",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc54494198",
        "coinTypeId": "ct55273427",
        "active": true,
        "premium": "1.4",
        "purchaseDate": "03/09/2015",
        "purchasePrice": "18.93",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc54510440",
        "coinTypeId": "ct20885143",
        "active": true,
        "premium": "8",
        "purchaseDate": "04/14/2015",
        "purchasePrice": "5.5",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc54543621",
        "coinTypeId": "ct38826467",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "05/28/2015",
        "purchasePrice": "42.54",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc55500450",
        "coinTypeId": "ct05959409",
        "active": true,
        "premium": "1.2",
        "purchaseDate": "05/28/2015",
        "purchasePrice": "17.52",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc55544996",
        "coinTypeId": "ct20885143",
        "active": true,
        "premium": "8",
        "purchaseDate": "04/14/2015",
        "purchasePrice": "5.5",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc56057759",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc56068726",
        "coinTypeId": "ct28857485",
        "active": true,
        "premium": "1.2",
        "purchaseDate": "03/06/2015",
        "purchasePrice": "10.98",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc56671622",
        "coinTypeId": "ct16288086",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc57010661",
        "coinTypeId": "ct21764365",
        "active": false,
        "premium": "1.36",
        "purchaseDate": "04/05/2015",
        "purchasePrice": "20.505",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc57492208",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc58420386",
        "coinTypeId": "ct77688385",
        "active": true,
        "premium": "5",
        "purchaseDate": "08/14/2015",
        "purchasePrice": "43.80",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc58860400",
        "coinTypeId": "ct41912587",
        "active": true,
        "premium": "6.49",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "3",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc58863068",
        "coinTypeId": "ct08254404",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "09/28/2015",
        "purchasePrice": "22.45",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc58888060",
        "coinTypeId": "ct85253214",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc59163874",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "02/08/2016",
        "purchasePrice": "20.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc59944960",
        "coinTypeId": "ct03395421",
        "active": true,
        "premium": "1.6",
        "purchaseDate": "11/18/2016",
        "purchasePrice": "9.5",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc60231442",
        "coinTypeId": "ct74472416",
        "active": true,
        "premium": "1.24",
        "purchaseDate": "04/20/2015",
        "purchasePrice": "18.7",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc60284852",
        "coinTypeId": "ct51188092",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc60343363",
        "coinTypeId": "ct69504395",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc60463945",
        "coinTypeId": "ct29783668",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc60919972",
        "coinTypeId": "ct30726160",
        "active": true,
        "premium": "1.45",
        "purchaseDate": "04/24/2015",
        "purchasePrice": "19.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc62023954",
        "coinTypeId": "mc87359291",
        "active": true,
        "premium": "1",
        "purchaseDate": "10/03/2015",
        "purchasePrice": 19.5,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc63523583",
        "coinTypeId": "ct92063722",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc64193096",
        "coinTypeId": "ct34217442",
        "active": true,
        "premium": "1.35",
        "purchaseDate": "08/26/2015",
        "purchasePrice": "39.52",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc64968592",
        "coinTypeId": "ct10847964",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc65012270",
        "coinTypeId": "ct40145040",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc65132069",
        "coinTypeId": "ct72580571",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "12/25/2015",
        "purchasePrice": "18.20",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc65337398",
        "coinTypeId": "mc87359291",
        "active": true,
        "premium": "1.4",
        "purchaseDate": "12/25/2015",
        "purchasePrice": "18.2",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc65529279",
        "coinTypeId": "ct98328452",
        "active": false,
        "premium": "1",
        "purchaseDate": "07/26/2015",
        "purchasePrice": "20.85",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc66143718",
        "coinTypeId": "ct72968879",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc66594324",
        "coinTypeId": "ct08254404",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "09/28/2015",
        "purchasePrice": "22.45",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc66677958",
        "coinTypeId": "ct63325213",
        "active": true,
        "premium": "20",
        "purchaseDate": "01/12/2016",
        "purchasePrice": "10",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc67230798",
        "coinTypeId": "ct61705209",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc67397720",
        "coinTypeId": "ct66226815",
        "active": false,
        "premium": "1.15",
        "purchaseDate": "03/09/2015",
        "purchasePrice": "19.92",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc67406560",
        "coinTypeId": "mc87359291",
        "active": true,
        "premium": "1.4",
        "purchaseDate": "12/25/2015",
        "purchasePrice": "18.2",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc68445155",
        "coinTypeId": "ct37123672",
        "active": true,
        "premium": "1.6",
        "purchaseDate": "07/18/2015",
        "purchasePrice": "46",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc69605368",
        "coinTypeId": "ct74472416",
        "active": false,
        "premium": "1.24",
        "purchaseDate": "04/20/2015",
        "purchasePrice": "18.7",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc69655355",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "02/08/2016",
        "purchasePrice": "20.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc69996551",
        "coinTypeId": "ct98328452",
        "active": true,
        "premium": "1",
        "purchaseDate": "07/26/2015",
        "purchasePrice": "20.85",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc70040373",
        "coinTypeId": "ct40145040",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc70376789",
        "coinTypeId": "ct78096558",
        "active": true,
        "premium": "2",
        "purchaseDate": "05/01/2015",
        "purchasePrice": "31.13",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc70426087",
        "coinTypeId": "ct42752934",
        "active": true,
        "premium": "1.3",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc70499353",
        "coinTypeId": "ct74516526",
        "active": true,
        "premium": "3.5",
        "purchaseDate": "11/18/205",
        "purchasePrice": "2",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc70737965",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "02/08/2016",
        "purchasePrice": "20.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc71001861",
        "coinTypeId": "ct45860574",
        "active": true,
        "premium": "7",
        "purchaseDate": "05/20/2015",
        "purchasePrice": "10",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc71005348",
        "coinTypeId": "ct34217442",
        "active": true,
        "premium": "1.35",
        "purchaseDate": "08/26/2015",
        "purchasePrice": "39.52",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc71961606",
        "coinTypeId": "ct93859603",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc72401099",
        "coinTypeId": "ct77065970",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "5",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc72601263",
        "coinTypeId": "ct97841652",
        "active": true,
        "premium": "1.73",
        "purchaseDate": "11/18/2015",
        "purchasePrice": "22",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc72972797",
        "coinTypeId": "ct43305428",
        "active": true,
        "premium": "1.2",
        "purchaseDate": "05/28/2015",
        "purchasePrice": "204.62",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc73006964",
        "coinTypeId": "ct08254004",
        "active": true,
        "premium": "1.84",
        "purchaseDate": "04/30/2015",
        "purchasePrice": "027",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc73028784",
        "coinTypeId": "ct61705209",
        "active": true,
        "premium": "2",
        "purchaseDate": "02/13/2016",
        "purchasePrice": "11",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc73574374",
        "coinTypeId": "ct55652876",
        "active": true,
        "premium": "2.1",
        "purchaseDate": "07/13/2015",
        "purchasePrice": "13.27",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc74082973",
        "coinTypeId": "ct21957452",
        "active": true,
        "premium": "1",
        "purchaseDate": "05/28/2015",
        "purchasePrice": "1.07",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc74610849",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1.5",
        "purchaseDate": "02/08/2016",
        "purchasePrice": "20.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc75216031",
        "coinTypeId": "ct37549734",
        "active": true,
        "premium": "1.3",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc75350222",
        "coinTypeId": "ct63873757",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc75657194",
        "coinTypeId": "ct79036780",
        "active": false,
        "premium": "1.6",
        "purchaseDate": "03/25/2015",
        "purchasePrice": "21.06",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc75738275",
        "coinTypeId": "ct98328452",
        "active": true,
        "premium": "1",
        "purchaseDate": "07/26/2015",
        "purchasePrice": "20.85",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc75989743",
        "coinTypeId": "ct65841055",
        "active": true,
        "premium": "2.5",
        "purchaseDate": "08/26/2015",
        "purchasePrice": "33",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc76195727",
        "coinTypeId": "ct08254404",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "09/28/2015",
        "purchasePrice": "22.45",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc76766415",
        "coinTypeId": "ct20885143",
        "active": true,
        "premium": "8",
        "purchaseDate": "04/14/2015",
        "purchasePrice": "5.5",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc77479096",
        "coinTypeId": "ct74472416",
        "active": false,
        "premium": "1.24",
        "purchaseDate": "04/20/2015",
        "purchasePrice": "18.7",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc78058290",
        "coinTypeId": "ct37914629",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc78230806",
        "coinTypeId": "ct20206923",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc78524738",
        "coinTypeId": "ct08537300",
        "active": true,
        "premium": "2.8",
        "purchaseDate": "06/25/2015",
        "purchasePrice": "14",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc79823812",
        "coinTypeId": "ct32247169",
        "active": true,
        "premium": "2",
        "purchaseDate": "02/13/2016",
        "purchasePrice": "9",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc83764839",
        "coinTypeId": "ct75736717",
        "active": true,
        "premium": "25",
        "purchaseDate": "01/12/2016",
        "purchasePrice": "18",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc84207749",
        "coinTypeId": "ct54246434",
        "active": true,
        "premium": "2",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "9",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc84540298",
        "coinTypeId": "ct55652876",
        "active": true,
        "premium": "2.1",
        "purchaseDate": "07/13/2015",
        "purchasePrice": "13.04",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc84740479",
        "coinTypeId": "ct30726160",
        "active": true,
        "premium": "1.45",
        "purchaseDate": "04/24/2015",
        "purchasePrice": "19.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc84783207",
        "coinTypeId": "ct57657879",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc85153301",
        "coinTypeId": "ct74472416",
        "active": true,
        "premium": "1.24",
        "purchaseDate": "04/20/2015",
        "purchasePrice": "18.7",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc85393354",
        "coinTypeId": "ct99542018",
        "active": true,
        "premium": "1.4",
        "purchaseDate": "06/26/2015",
        "purchasePrice": "19.47",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc86363929",
        "coinTypeId": "ct70844198",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc86783166",
        "coinTypeId": "ct99542018",
        "active": true,
        "premium": "1",
        "purchaseDate": "10/03/2015",
        "purchasePrice": 19.5,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc88200136",
        "coinTypeId": "ct98328452",
        "active": true,
        "premium": "1",
        "purchaseDate": "07/26/2015",
        "purchasePrice": "20.85",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc89419983",
        "coinTypeId": "ct22798609",
        "active": true,
        "premium": "1.25",
        "purchaseDate": "03/28/2015",
        "purchasePrice": "20.53",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc90158100",
        "coinTypeId": "ct17114119",
        "active": true,
        "premium": "1.6",
        "purchaseDate": "10/01/2015",
        "purchasePrice": "18",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc90893957",
        "coinTypeId": "ct26414953",
        "active": true,
        "premium": "2",
        "purchaseDate": "07/05/2015",
        "purchasePrice": "6.34",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc91228316",
        "coinTypeId": "ct62921249",
        "active": false,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc91748954",
        "coinTypeId": "ct03395421",
        "active": true,
        "premium": "1.6",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "10",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc92385531",
        "coinTypeId": "ct99542018",
        "active": true,
        "premium": "1.4",
        "purchaseDate": "06/26/2015",
        "purchasePrice": "19.47",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc94304517",
        "coinTypeId": "ct26414953",
        "active": true,
        "premium": "2",
        "purchaseDate": "07/05/2015",
        "purchasePrice": "6.34",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc94963019",
        "coinTypeId": "ct34217442",
        "active": true,
        "premium": "1.35",
        "purchaseDate": "08/26/2015",
        "purchasePrice": "39.52",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc95150226",
        "coinTypeId": "ct97175998",
        "active": true,
        "premium": "1.3",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc95694106",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc95767068",
        "coinTypeId": "ct99542018",
        "active": true,
        "premium": "1",
        "purchaseDate": "10/03/2015",
        "purchasePrice": 19.5,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc96479465",
        "coinTypeId": "mc76180889",
        "active": true,
        "premium": "1",
        "purchaseDate": "10/03/2015",
        "purchasePrice": 19.5,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc96489654",
        "coinTypeId": "ct02099974",
        "active": true,
        "premium": "1",
        "purchaseDate": "",
        "purchasePrice": 0,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc96644434",
        "coinTypeId": "ct99542018",
        "active": true,
        "premium": "1",
        "purchaseDate": "10/03/2015",
        "purchasePrice": 19.5,
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc97134041",
        "coinTypeId": "ct38826467",
        "active": true,
        "premium": "1.8",
        "purchaseDate": "01/12/2016",
        "purchasePrice": "51",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc97180030",
        "coinTypeId": "ct63718583",
        "active": true,
        "premium": "1.65",
        "purchaseDate": "05/04/2015",
        "purchasePrice": "21.17",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc97222744",
        "coinTypeId": "ct63569826",
        "active": true,
        "premium": "1.33",
        "purchaseDate": "09/17/2015",
        "purchasePrice": "82.24",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc97960205",
        "coinTypeId": "ct91069558",
        "active": true,
        "premium": "1.3",
        "purchaseDate": "05/30/2015",
        "purchasePrice": "45",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": true
    }, {
        "id": "mc98291421",
        "coinTypeId": "ct14845987",
        "active": true,
        "premium": "2",
        "purchaseDate": "02/06/2016",
        "purchasePrice": "6",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc98821088",
        "coinTypeId": "ct74472416",
        "active": true,
        "premium": "1.24",
        "purchaseDate": "04/20/2015",
        "purchasePrice": "18.7",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }, {
        "id": "mc99437858",
        "coinTypeId": "ct30726160",
        "active": true,
        "premium": "1.45",
        "purchaseDate": "04/24/2015",
        "purchasePrice": "19.25",
        "saleDate": "",
        "salePrice": "",
        "isPermaStack": false
    }],
    "coinTypes": [{
        "id": "ct00317870",
        "country": "Australia",
        "year": "2013",
        "mint": "Perth Mint",
        "series": "Koala",
        "weight": "0.5",
        "width": "2.3",
        "metal": "silver",
        "diameter": "36.6"
    }, {
        "id": "ct01021621",
        "country": "Australia",
        "year": "2013",
        "mint": "Perth Mint",
        "series": "Koala",
        "weight": 1,
        "width": 4,
        "metal": "silver",
        "diameter": 40.6
    }, {
        "id": "ct02099974",
        "country": "Mexico",
        "year": 2014,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 40.6
    }, {
        "id": "ct02559777",
        "country": "Mexico",
        "year": "1944",
        "mint": "Casa De Moneda",
        "series": "1 Peso",
        "weight": "0.3856",
        "width": "2.2",
        "metal": "silver",
        "diameter": "34.1"
    }, {
        "id": "ct03395421",
        "country": "Mexico",
        "year": 1968,
        "mint": "Casa De Moneda",
        "series": "25 pesos",
        "weight": 0.5209,
        "width": 2.5,
        "metal": "silver",
        "diameter": 39
    }, {
        "id": "ct03969878",
        "country": "Australia",
        "year": 2015,
        "mint": "Perth Mint",
        "series": "Koala",
        "weight": 1,
        "width": 4,
        "metal": "silver",
        "diameter": 40.6
    }, {
        "id": "ct05959409",
        "country": "USA",
        "year": 2015,
        "mint": "Provident Mint",
        "series": "Año De La Cabra",
        "weight": 1,
        "width": "--",
        "metal": "silver",
        "diameter": 40
    }, {
        "id": "ct08166697",
        "country": "Mexico",
        "year": "1928",
        "mint": "Casa De Moneda",
        "series": "20 centavos",
        "weight": "0.07709076878558",
        "width": "1.18",
        "metal": "silver",
        "diameter": "19"
    }, {
        "id": "ct08254004",
        "country": "Australia",
        "year": 2015,
        "mint": "Perth Mint",
        "series": "Lunar",
        "weight": 1,
        "width": 4,
        "metal": "silver",
        "diameter": 45.6
    }, {
        "id": "ct08254404",
        "country": "China",
        "year": 2015,
        "mint": "China",
        "series": "Panda",
        "weight": 1,
        "width": "3.2",
        "metal": "silver",
        "diameter": "40"
    }, {
        "id": "ct08537300",
        "country": "Australia",
        "year": "2013",
        "mint": "Perth Mint",
        "series": "Lunar",
        "weight": "0.5",
        "width": "2.3",
        "metal": "silver",
        "diameter": "36.6"
    }, {
        "id": "ct10847964",
        "country": "Mexico",
        "year": 1966,
        "mint": "Casa De Moneda",
        "series": "1 Peso",
        "weight": 0.051441,
        "width": 2.5,
        "metal": "silver",
        "diameter": 34.5
    }, {
        "id": "ct11082869",
        "country": "USA",
        "year": "1917",
        "mint": "US Mint",
        "series": "10 cents",
        "weight": "0.07234494067715",
        "width": "1",
        "metal": "silver",
        "diameter": "17.9"
    }, {
        "id": "ct11451255",
        "country": "Mexico",
        "year": 2013,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 2,
        "width": 4.5,
        "metal": "silver",
        "diameter": 48
    }, {
        "id": "ct11919037",
        "country": "Italy",
        "year": "1863",
        "mint": "Rome",
        "series": "1 Lira",
        "weight": "0.1342",
        "width": "1.5",
        "metal": "silver",
        "diameter": "23"
    }, {
        "id": "ct14845987",
        "country": "Suiza",
        "year": "1932",
        "mint": "B",
        "series": "5 Franken",
        "weight": "0.4027",
        "width": "--",
        "metal": "silver",
        "diameter": "31.45"
    }, {
        "id": "ct15191701",
        "country": "USA",
        "year": "",
        "mint": "Sunshine Mint",
        "series": "Buffalo",
        "weight": 1,
        "width": 2.8,
        "metal": "silver",
        "diameter": 39
    }, {
        "id": "ct16288086",
        "country": "Mexico",
        "year": 1978,
        "mint": "Casa De Moneda",
        "series": "100 Pesos",
        "weight": 0.643,
        "width": 2.9,
        "metal": "silver",
        "diameter": 40
    }, {
        "id": "ct16757622",
        "country": "Mexico",
        "year": 1957,
        "mint": "Casa De Moneda",
        "series": "1 Peso",
        "weight": 0.051441,
        "width": 2.5,
        "metal": "silver",
        "diameter": 34.5
    }, {
        "id": "ct17114119",
        "country": "Mexico",
        "year": "2002",
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 40.6
    }, {
        "id": "ct17546876",
        "country": "Canada",
        "year": "2015",
        "mint": "Royal Canadian Mint",
        "series": "RCM Bar",
        "weight": "10",
        "width": 3.29,
        "metal": "silver",
        "diameter": "90"
    }, {
        "id": "ct17598979",
        "country": "Mexico",
        "year": "1905",
        "mint": "Casa De Moneda",
        "series": "10 centavos",
        "weight": "0.06430661393524",
        "width": "1.18",
        "metal": "silver",
        "diameter": "18"
    }, {
        "id": "ct19265545",
        "country": "Australia",
        "year": 2015,
        "mint": "Perth Mint",
        "series": "Kookaburra",
        "weight": 10,
        "width": 8.7,
        "metal": "silver",
        "diameter": 75.6
    }, {
        "id": "ct19401019",
        "country": "Mexico",
        "year": "1977",
        "mint": "Casa De Moneda",
        "series": "100 Pesos",
        "weight": 0.643,
        "width": 2.9,
        "metal": "silver",
        "diameter": 40
    }, {
        "id": "ct20170447",
        "country": "Mexico",
        "year": 2008,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 40.6
    }, {
        "id": "ct20206923",
        "country": "Mexico",
        "year": "1956",
        "mint": "Casa De Moneda",
        "series": "10 Pesos Hidalgo",
        "weight": 0.643,
        "width": 2.9,
        "metal": "silver",
        "diameter": 40
    }, {
        "id": "ct20885143",
        "country": "Mexico",
        "year": 1992,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 0.05,
        "width": 1,
        "metal": "silver",
        "diameter": 16
    }, {
        "id": "ct21764365",
        "country": "GranBretaña",
        "year": 2015,
        "mint": "British Royal Mint",
        "series": "Britania",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 38.61
    }, {
        "id": "ct21957452",
        "country": "USA",
        "year": 2015,
        "mint": "Provident Mint",
        "series": "Año De La Cabra",
        "weight": 1,
        "width": "--",
        "metal": "copper",
        "diameter": 40
    }, {
        "id": "ct21984109",
        "country": "Australia",
        "year": "2013",
        "mint": "Perth Mint",
        "series": "Lunar Colorized(Proof)",
        "weight": "0.5",
        "width": "2.3",
        "metal": "silver",
        "diameter": "36.6"
    }, {
        "id": "ct22798609",
        "country": "Austria",
        "year": 2014,
        "mint": "Austrian mint",
        "series": "Filarmónica",
        "weight": 1,
        "width": 3.2,
        "metal": "silver",
        "diameter": 37
    }, {
        "id": "ct24990040",
        "country": "USA",
        "year": "",
        "mint": "WestminsterMint",
        "series": "Pope Francis",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 39
    }, {
        "id": "ct25537124",
        "country": "Australia",
        "year": 2015,
        "mint": "Perth Mint",
        "series": "Lunar",
        "weight": "2",
        "width": "3.6",
        "metal": "silver",
        "diameter": "55.6"
    }, {
        "id": "ct26414953",
        "country": "Suiza",
        "year": "1954",
        "mint": "B",
        "series": "5 Franken",
        "weight": "0.4027",
        "width": "--",
        "metal": "silver",
        "diameter": "31.45"
    }, {
        "id": "ct27664483",
        "country": "Australia",
        "year": 2013,
        "mint": "Perth Mint",
        "series": "Lunar",
        "weight": "2",
        "width": "3.6",
        "metal": "silver",
        "diameter": "55.6"
    }, {
        "id": "ct28003062",
        "country": "Australia",
        "year": "2013",
        "mint": "Perth Mint",
        "series": "Lunar",
        "weight": 1,
        "width": 2.6,
        "metal": "silver",
        "diameter": 45.6
    }, {
        "id": "ct28857485",
        "country": "-",
        "year": "",
        "mint": "-",
        "series": "handpour",
        "weight": 0.5,
        "width": "--",
        "metal": "silver",
        "diameter": "--"
    }, {
        "id": "ct29189310",
        "country": "Mexico",
        "year": 2015,
        "mint": "Casa De Moneda",
        "series": "Libertad (proof)",
        "weight": 0.05,
        "width": 1,
        "metal": "silver",
        "diameter": 16
    }, {
        "id": "ct29783668",
        "country": "Mexico",
        "year": 1953,
        "mint": "Casa De Moneda",
        "series": "5 Pesos Año De Hidalgo",
        "weight": 0.643,
        "width": 2.9,
        "metal": "silver",
        "diameter": 40
    }, {
        "id": "mc30447922",
        "country": "Mexico",
        "year": 2011,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 40.6
    }, {
        "id": "ct30726160",
        "country": "USA",
        "year": 2015,
        "mint": "US Mint",
        "series": "Silver Eagle",
        "weight": 1,
        "width": 2.98,
        "metal": "silver",
        "diameter": 40.6
    }, {
        "id": "ct30773496",
        "country": "Mexico",
        "year": 2015,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 0.05,
        "width": 1,
        "metal": "silver",
        "diameter": 16
    }, {
        "id": "ct32014901",
        "country": "USA",
        "year": "",
        "mint": "Provident Mint",
        "series": "Dogecoin",
        "weight": 1,
        "width": "--",
        "metal": "silver",
        "diameter": 39
    }, {
        "id": "ct32247169",
        "country": "Mexico",
        "year": "1938",
        "mint": "Casa De Moneda",
        "series": "1 Peso",
        "weight": "0.3856",
        "width": "2.2",
        "metal": "silver",
        "diameter": "34.1"
    }, {
        "id": "ct34217442",
        "country": "USA",
        "year": 2015,
        "mint": "Provident Mint",
        "series": "Privateer II",
        "weight": 2,
        "width": "--",
        "metal": "silver",
        "diameter": 40
    }, {
        "id": "ct36352600",
        "country": "Australia",
        "year": 2015,
        "mint": "Perth Mint",
        "series": "Lunar",
        "weight": "5",
        "width": "5.8",
        "metal": "silver",
        "diameter": "65.6"
    }, {
        "id": "ct37123672",
        "country": "Mexico",
        "year": 2015,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": "2",
        "width": "4.5",
        "metal": "silver",
        "diameter": "48"
    }, {
        "id": "ct37549734",
        "country": "USA",
        "year": "1923",
        "mint": "US Mint",
        "series": "10 cents",
        "weight": "0.07234494067715",
        "width": "1",
        "metal": "silver",
        "diameter": "17.9"
    }, {
        "id": "ct37914629",
        "country": "Mexico",
        "year": 1959,
        "mint": "Casa De Moneda",
        "series": "1 Peso",
        "weight": 0.051441,
        "width": 2.5,
        "metal": "silver",
        "diameter": 34.5
    }, {
        "id": "ct38676191",
        "country": "Mexico",
        "year": "1950",
        "mint": "Casa De Moneda",
        "series": "1 Peso",
        "weight": "0.1285810745635",
        "width": "2",
        "metal": "silver",
        "diameter": "32"
    }, {
        "id": "ct38826467",
        "country": "USA",
        "year": 2015,
        "mint": "Provident Mint",
        "series": "Privateer I",
        "weight": 2,
        "width": "--",
        "metal": "silver",
        "diameter": 40
    }, {
        "id": "ct40145040",
        "country": "Mexico",
        "year": 2005,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 40.6
    }, {
        "id": "ct41912587",
        "country": "Mexico",
        "year": "1950",
        "mint": "Casa De Moneda",
        "series": "25 centavos",
        "weight": "0.03212115366065",
        "width": "1",
        "metal": "silver",
        "diameter": "21"
    }, {
        "id": "ct42752934",
        "country": "USA",
        "year": "1916",
        "mint": "US Mint",
        "series": "10 cents",
        "weight": "0.07234494067715",
        "width": "1",
        "metal": "silver",
        "diameter": "17.9"
    }, {
        "id": "ct43305428",
        "country": "Australia",
        "year": 2015,
        "mint": "Perth Mint",
        "series": "Lunar",
        "weight": "10",
        "width": "6.6",
        "metal": "silver",
        "diameter": "85.6"
    }, {
        "id": "ct43829769",
        "country": "Mexico",
        "year": "1947",
        "mint": "Casa De Moneda",
        "series": "1 Peso",
        "weight": ".2250",
        "width": "2",
        "metal": "silver",
        "diameter": "32"
    }, {
        "id": "ct44182242",
        "country": "Australia",
        "year": 2015,
        "mint": "Perth Mint",
        "series": "Lunar Series II",
        "weight": 0.1,
        "width": 2,
        "metal": "gold",
        "diameter": 18.6
    }, {
        "id": "ct45860574",
        "country": "Mexico",
        "year": 2015,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 0.1,
        "width": 1.4,
        "metal": "silver",
        "diameter": 20
    }, {
        "id": "ct47283102",
        "country": "Mexico",
        "year": "1943",
        "mint": "Casa De Moneda",
        "series": "1 Peso",
        "weight": "0.3856",
        "width": "2.2",
        "metal": "silver",
        "diameter": "34.1"
    }, {
        "id": "ct48297131",
        "country": "Canada",
        "year": 2015,
        "mint": "Royal Canadian Mint",
        "series": "Maple (Goat Privy)",
        "weight": 1,
        "width": 3.29,
        "metal": "silver",
        "diameter": 38
    }, {
        "id": "ct49264661",
        "country": "Mexico",
        "year": 1968,
        "mint": "Casa De Moneda",
        "series": "25 pesos (Juarez)",
        "weight": 0.5209,
        "width": 2.5,
        "metal": "silver",
        "diameter": "38"
    }, {
        "id": "ct51188092",
        "country": "USA",
        "year": 2014,
        "mint": "US Mint",
        "series": "Silver Eagle",
        "weight": 1,
        "width": 2.98,
        "metal": "silver",
        "diameter": 40.6
    }, {
        "id": "ct54246434",
        "country": "South Africa",
        "year": "1959",
        "mint": "-",
        "series": "2 1/2 Shillings",
        "weight": "0.2273238802611",
        "width": "2",
        "metal": "silver",
        "diameter": "32.3"
    }, {
        "id": "ct55273427",
        "country": "GranBretaña",
        "year": 2014,
        "mint": "British Royal Mint",
        "series": "Año Del Caballo",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 38.61
    }, {
        "id": "ct55652876",
        "country": "Australia",
        "year": 2015,
        "mint": "Perth Mint",
        "series": "Lunar",
        "weight": "0.5",
        "width": "2.3",
        "metal": "silver",
        "diameter": "36.3"
    }, {
        "id": "ct56306150",
        "country": "Mexico",
        "year": 1985,
        "mint": "Casa De Moneda",
        "series": "Mexico 86",
        "weight": 0.719988,
        "width": "--",
        "metal": "silver",
        "diameter": 38
    }, {
        "id": "ct57021566",
        "country": "Suiza",
        "year": "",
        "mint": "PAMP Suisse",
        "series": "Fortuna",
        "weight": 0.03215,
        "width": "--",
        "metal": "platinum",
        "diameter": "--"
    }, {
        "id": "ct57657879",
        "country": "Mexico",
        "year": "1932",
        "mint": "Casa De Moneda",
        "series": "1 Peso",
        "weight": "0.3856",
        "width": "2.2",
        "metal": "silver",
        "diameter": "34.1"
    }, {
        "id": "ct59330439",
        "country": "Mexico",
        "year": 2013,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 0.05,
        "width": 1,
        "metal": "silver",
        "diameter": 16
    }, {
        "id": "ct59717514",
        "country": "Mexico",
        "year": 1979,
        "mint": "Casa De Moneda",
        "series": "Onza-balanza",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 41.5
    }, {
        "id": "ct61705209",
        "country": "Mexico",
        "year": "1940",
        "mint": "Casa De Moneda",
        "series": "1 Peso",
        "weight": "0.3856",
        "width": "2.2",
        "metal": "silver",
        "diameter": "34.1"
    }, {
        "id": "ct62921249",
        "country": "Austria",
        "year": 2015,
        "mint": "Austrian mint",
        "series": "Filarmónica",
        "weight": 1,
        "width": 3.2,
        "metal": "silver",
        "diameter": 37
    }, {
        "id": "ct63325213",
        "country": "Mexico",
        "year": 2014,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 0.05,
        "width": 1,
        "metal": "silver",
        "diameter": 16
    }, {
        "id": "ct63335213",
        "country": "Mexico",
        "year": 2014,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 0.1,
        "width": 1.4,
        "metal": "silver",
        "diameter": 20
    }, {
        "id": "ct63345213",
        "country": "Mexico",
        "year": 2014,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 0.25,
        "width": 1.7,
        "metal": "silver",
        "diameter": 27
    }, {
        "id": "ct63569826",
        "country": "Mexico",
        "year": "1945",
        "mint": "Casa De Moneda",
        "series": "2.5 Pesos Hidalgo",
        "weight": "0.0603",
        "width": "0.86",
        "metal": "gold",
        "diameter": "15.5"
    }, {
        "id": "ct63718583",
        "country": "Mexico",
        "year": 1984,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 1,
        "width": 4,
        "metal": "silver",
        "diameter": 36
    }, {
        "id": "ct63873757",
        "country": "Mexico",
        "year": 2003,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 40.6
    }, {
        "id": "ct63874757",
        "country": "Mexico",
        "year": "2004",
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 40.6
    }, {
        "id": "ct65193802",
        "country": "USA",
        "year": "2013",
        "mint": "APMEX",
        "series": "Lunar Snake",
        "weight": 1,
        "width": 3.2,
        "metal": "silver",
        "diameter": "38.6"
    }, {
        "id": "ct65841055",
        "country": "Australia",
        "year": "2013",
        "mint": "Perth Mint",
        "series": "Lunar Colorized",
        "weight": 1,
        "width": 2.6,
        "metal": "silver",
        "diameter": 45.6
    }, {
        "id": "ct65845301",
        "country": "Mexico",
        "year": "2015",
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 0.5,
        "width": 2.6,
        "metal": "silver",
        "diameter": 33
    }, {
        "id": "ct66226815",
        "country": "USA",
        "year": "",
        "mint": "Golden State Mint",
        "series": "Standing Liberty",
        "weight": 1,
        "width": 3.2,
        "metal": "silver",
        "diameter": 39.3
    }, {
        "id": "ct66931955",
        "country": "Mexico",
        "year": "1993",
        "mint": "Casa De Moneda",
        "series": "20 Nuevos Pesos",
        "weight": "0.5054917848301",
        "width": 2.9,
        "metal": "silver",
        "diameter": "32"
    }, {
        "id": "ct68985861",
        "country": "Mexico",
        "year": 1957,
        "mint": "Casa De Moneda",
        "series": "1 Peso (Juarez)",
        "weight": 0.051441,
        "width": 2.5,
        "metal": "silver",
        "diameter": 34.5
    }, {
        "id": "ct69138694",
        "country": "España",
        "year": 1990,
        "mint": "FNMT",
        "series": "Olimpiadas-fútbol",
        "weight": 1,
        "width": "--",
        "metal": "silver",
        "diameter": 40
    }, {
        "id": "ct69504395",
        "country": "Mexico",
        "year": "2015",
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 0.25,
        "width": 1.5,
        "metal": "silver",
        "diameter": 27
    }, {
        "id": "ct70844198",
        "country": "Mexico",
        "year": 2014,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 5,
        "width": 5.05,
        "metal": "silver",
        "diameter": 65
    }, {
        "id": "ct71587476",
        "country": "GranBretaña",
        "year": "2015",
        "mint": "British Royal Mint",
        "series": "Año De La Cabra",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 38.61
    }, {
        "id": "ct72580571",
        "country": "Mexico",
        "year": "1990",
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 1,
        "width": 4,
        "metal": "silver",
        "diameter": 36
    }, {
        "id": "ct72968879",
        "country": "Mexico",
        "year": "2008",
        "mint": "Casa De Moneda",
        "series": "100 Pesos (Chihuahua)",
        "weight": "1.009436995595",
        "width": "3",
        "metal": "silver",
        "diameter": "39.04"
    }, {
        "id": "ct73704560",
        "country": "Mexico",
        "year": "1979",
        "mint": "Casa De Moneda",
        "series": "100 Pesos",
        "weight": 0.643,
        "width": 2.9,
        "metal": "silver",
        "diameter": 40
    }, {
        "id": "ct74472416",
        "country": "Canada",
        "year": 2015,
        "mint": "Royal Canadian Mint",
        "series": "Maple",
        "weight": 1,
        "width": 3.29,
        "metal": "silver",
        "diameter": 38
    }, {
        "id": "ct74516526",
        "country": "Mexico",
        "year": "1782",
        "mint": "Casa De Moneda",
        "series": "1/2 Real",
        "weight": "0.04122",
        "width": "0.9",
        "metal": "silver",
        "diameter": "17.2"
    }, {
        "id": "ct75736717",
        "country": "Mexico",
        "year": "2014",
        "mint": "Casa De Moneda",
        "series": "Libertad (proof)",
        "weight": 0.05,
        "width": 1,
        "metal": "silver",
        "diameter": 16
    }, {
        "id": "mc76180889",
        "country": "Mexico",
        "year": 2006,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 40.6
    }, {
        "id": "ct77065970",
        "country": "Mexico",
        "year": "1943",
        "mint": "Casa De Moneda",
        "series": "50 Centavos",
        "weight": "0.192842673869",
        "width": "2",
        "metal": "silver",
        "diameter": "27"
    }, {
        "id": "ct77483911",
        "country": "Mexico",
        "year": 1992,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 1,
        "width": 4,
        "metal": "silver",
        "diameter": 36
    }, {
        "id": "ct77605757",
        "country": "Mexico",
        "year": "1947",
        "mint": "Casa De Moneda",
        "series": "5 Pesos Cuhahutemoc",
        "weight": "0.8681392881258",
        "width": "4",
        "metal": "silver",
        "diameter": 40
    }, {
        "id": "ct77688385",
        "country": "Australia",
        "year": "2013",
        "mint": "Perth Mint",
        "series": "Lunar Colorized(Proof)",
        "weight": "1",
        "width": "2.3",
        "metal": "silver",
        "diameter": "40.6"
    }, {
        "id": "ct78096558",
        "country": "Suiza",
        "year": 2013,
        "mint": "PAMP Suisse",
        "series": "Año De La Serpiente",
        "weight": 1,
        "width": 2.66,
        "metal": "silver",
        "diameter": "27x47"
    }, {
        "id": "ct78297046",
        "country": "Suiza",
        "year": 2015,
        "mint": "PAMP Suisse",
        "series": "Año De La Cabra",
        "weight": 0.3215,
        "width": "--",
        "metal": "silver",
        "diameter": "--"
    }, {
        "id": "ct79036780",
        "country": "Australia",
        "year": 2015,
        "mint": "Perth Mint",
        "series": "Kookaburra",
        "weight": 1,
        "width": 4,
        "metal": "silver",
        "diameter": 40
    }, {
        "id": "ct80375315",
        "country": "Mexico",
        "year": "1933",
        "mint": "Casa De Moneda",
        "series": "1 Peso",
        "weight": "0.3856",
        "width": "2.2",
        "metal": "silver",
        "diameter": "34.1"
    }, {
        "id": "ct81285961",
        "country": "Mexico",
        "year": 2014,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 2,
        "width": 4.5,
        "metal": "silver",
        "diameter": 48
    }, {
        "id": "ct85253214",
        "country": "Mexico",
        "year": 1964,
        "mint": "Casa De Moneda",
        "series": "1 Peso",
        "weight": 0.051441,
        "width": 2.5,
        "metal": "silver",
        "diameter": 34.5
    }, {
        "id": "mc87359291",
        "country": "Mexico",
        "year": 2012,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 40.6
    }, {
        "id": "ct87596361",
        "country": "Australia",
        "year": "2013",
        "mint": "Perth Mint",
        "series": "Lunar Colorized",
        "weight": "0.5",
        "width": "2.3",
        "metal": "silver",
        "diameter": "36.6"
    }, {
        "id": "ct89115132",
        "country": "Australia",
        "year": 2015,
        "mint": "Perth Mint",
        "series": "Lunar Colorized",
        "weight": 1,
        "width": 4,
        "metal": "silver",
        "diameter": 45.6
    }, {
        "id": "ct90311804",
        "country": "Suiza",
        "year": "",
        "mint": "PAMP Suisse",
        "series": "Fortuna",
        "weight": 1,
        "width": 2.66,
        "metal": "silver",
        "diameter": "27x47"
    }, {
        "id": "ct91069558",
        "country": "Suiza",
        "year": "",
        "mint": "PAMP Suisse",
        "series": "Fortuna",
        "weight": 0.03215,
        "width": "--",
        "metal": "gold",
        "diameter": "--"
    }, {
        "id": "ct92063722",
        "country": "Mexico",
        "year": 2014,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 0.5,
        "width": 2.6,
        "metal": "silver",
        "diameter": 33
    }, {
        "id": "ct93859603",
        "country": "Mexico",
        "year": 1953,
        "mint": "Casa De Moneda",
        "series": "5 Pesos Hidalgo",
        "weight": 0.643,
        "width": 2.9,
        "metal": "silver",
        "diameter": 40
    }, {
        "id": "ct95447310",
        "country": "Mexico",
        "year": 1991,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 1,
        "width": 4,
        "metal": "silver",
        "diameter": 36
    }, {
        "id": "ct96533562",
        "country": "Turquía",
        "year": "",
        "mint": "IRB",
        "series": "Barra",
        "weight": 0.080376,
        "width": "--",
        "metal": "gold",
        "diameter": "--"
    }, {
        "id": "ct97175998",
        "country": "USA",
        "year": "1945",
        "mint": "US Mint",
        "series": "10 cents",
        "weight": "0.07234494067715",
        "width": "1",
        "metal": "silver",
        "diameter": "17.9"
    }, {
        "id": "ct97233002",
        "country": "Mexico",
        "year": "1922",
        "mint": "Casa De Moneda",
        "series": "1 Peso",
        "weight": "0.3856",
        "width": "2.2",
        "metal": "silver",
        "diameter": "34.1"
    }, {
        "id": "ct97841652",
        "country": "Mexico",
        "year": "1948",
        "mint": "Casa De Moneda",
        "series": "5 Pesos Cuhahutemoc",
        "weight": "0.8681392881258",
        "width": "4",
        "metal": "silver",
        "diameter": 40
    }, {
        "id": "ct98328452",
        "country": "Mexico",
        "year": "1980",
        "mint": "Casa De Moneda",
        "series": "Onza-balanza",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 41.5
    }, {
        "id": "ct98804651",
        "country": "Mexico",
        "year": "1926",
        "mint": "Casa De Moneda",
        "series": "1 Peso",
        "weight": "0.3856",
        "width": "2.2",
        "metal": "silver",
        "diameter": "34.1"
    }, {
        "id": "ct99542018",
        "country": "Mexico",
        "year": 2015,
        "mint": "Casa De Moneda",
        "series": "Libertad",
        "weight": 1,
        "width": 3,
        "metal": "silver",
        "diameter": 40.6
    }]
};